# Generated by Django 3.0.4 on 2020-03-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='search',
            new_name='search1',
        ),
    ]
