# Generated by Django 3.0.4 on 2020-03-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_search_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='search1',
            new_name='search',
        ),
    ]
